version: '2.4' # 2.4 is the last version that supports depends_on conditions for service health
networks:
  cassandra:  # docker network where all cassandra nodes will be put in
services:
  cass1:
    image: stratio/cassandra-lucene-index:latest   # better to use a specific version, if you want to control upgrades
    container_name: cass1
    hostname: cass1
    mem_limit: 2g  # It's not strictly required, but it's better to have some memory limit

    networks:
      - cassandra
    ports:
      - "9042:9042"  # Expose native binary CQL port for your apps
    volumes:
      - ./ccc_data/cass1:/var/lib/cassandra    # This is the volume that will persist data for cass1 node
      - ./ccc/cass1:/opt/cassandra/conf   # Use your own config files for full control
    environment: &environment    # Declare and save environments variables into "environment"
        MAX_HEAP: 1G
        MAX_NEW: 64M
        SEEDS: 'cass1, cass2'

  cass2:
    image: stratio/cassandra-lucene-index:latest
    container_name: cass2
    hostname: cass2
    mem_limit: 2g

    networks:
      - cassandra
    ports:
      - "9043:9042"  # Expose native binary CQL port for your apps
    volumes:
      - ./ccc_data/cass2:/var/lib/cassandra    # This is the volume that will persist data for cass1 node
      - ./ccc/cass2:/opt/cassandra/conf   # Use your own config files for full control
    environment: *environment    # point to "environment" to use the same environment variables as cass1
    depends_on:
      - 'cass1'
  cass3:
    image: stratio/cassandra-lucene-index:latest
    container_name: cass3
    hostname: cass3
    mem_limit: 2g
    networks:
      - cassandra
    ports:
      - "9044:9042"  # Expose native binary CQL port for your apps
    volumes:
      - ./ccc_data/cass2:/var/lib/cassandra    # This is the volume that will persist data for cass1 node
      - ./ccc/cass2:/opt/cassandra/conf   # Use your own config files for full control
    environment: *environment    # point to "environment" to use the same environment variables as cass1
    depends_on:
      - 'cass2'